# Generated by Django 5.1.15 on 2026-09-09 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Title of this action (e.g. 'Open All Leads', 'Generate Invoice PDF').", max_length=150, verbose_name='Action Name')),
                ('action_type', models.CharField(choices=[('window', 'Open Window / Model View'), ('server', 'Run Server Action / Task'), ('report', 'Generate Printable Report'), ('url', 'Redirect to URL / Endpoint')], default='window', help_text='Classification of the operation executed.', max_length=20, verbose_name='Action Type')),
                ('domain_filter', models.JSONField(blank=True, default=dict, help_text="JSON query filter applied to the view (e.g. {'status': 'active'}).", verbose_name='Domain Filter')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Arbitrary context dictionary passed to the client or handler.', verbose_name='Context')),
                ('server_handler', models.CharField(blank=True, default='', help_text="Registered action handler identifier (for action_type='server').", max_length=200, verbose_name='Server Handler Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Metadata Action',
                'verbose_name_plural': 'Metadata Actions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MetaMenu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display label in navigation menus (e.g. 'CRM', 'Contacts', 'All Leads').", max_length=150, verbose_name='Menu Label')),
                ('icon', models.CharField(blank=True, default='folder', help_text="Icon identifier (e.g. 'users', 'briefcase', 'database').", max_length=64, verbose_name='Icon Slug')),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Display sequence order among sibling menus.', verbose_name='Sequence Order')),
                ('app_label', models.CharField(db_index=True, default='general', help_text='Module identifier owning this navigation menu.', max_length=100, verbose_name='Application Module')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('action', models.ForeignKey(blank=True, help_text='Action executed upon clicking this menu item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='meta_engine.metaaction', verbose_name='Attached Action')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent menu item for nested dropdowns or sub-menus.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='meta_engine.metamenu', verbose_name='Parent Menu')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Metadata Menu',
                'verbose_name_plural': 'Metadata Menus',
                'ordering': ['sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetaModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Unique programmatic model slug (e.g. 'contacts_partner', 'crm_lead').", max_length=100, unique=True, verbose_name='Model Identifier')),
                ('label', models.CharField(help_text="Human-readable singular label (e.g. 'Contact', 'Lead').", max_length=150, verbose_name='Display Label')),
                ('label_plural', models.CharField(blank=True, help_text="Human-readable plural label (e.g. 'Contacts', 'Leads').", max_length=150, verbose_name='Plural Label')),
                ('app_label', models.CharField(db_index=True, default='general', help_text="Logical module or package grouping (e.g. 'crm', 'contacts', 'invoicing').", max_length=100, verbose_name='Application Module')),
                ('table_name', models.CharField(db_index=True, help_text="Physical PostgreSQL table name (e.g. 'app_contacts_partner').", max_length=120, unique=True, verbose_name='Database Table Name')),
                ('description', models.TextField(blank=True, help_text='Purpose and business boundaries of this entity.', verbose_name='Description')),
                ('is_system', models.BooleanField(default=False, help_text='System models are protected against deletion.', verbose_name='Is System Protected')),
                ('is_auditable', models.BooleanField(default=True, help_text='If enabled, instances automatically track created_by, updated_by, created_at, updated_at.', verbose_name='Is Auditable')),
                ('is_soft_delete', models.BooleanField(default=False, help_text='If enabled, instances support paranoid soft deletion via SoftDeleteModel.', verbose_name='Supports Soft Delete')),
                ('is_active', models.BooleanField(default=True, help_text='Deactivated models are concealed from active navigation and API routes.', verbose_name='Is Active')),
                ('ordering_field', models.CharField(default='-created_at', help_text="Default sorting field expression (e.g. '-created_at', 'sequence', 'name').", max_length=100, verbose_name='Default Order Field')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Metadata Model',
                'verbose_name_plural': 'Metadata Models',
                'ordering': ['app_label', 'name'],
            },
        ),
        migrations.AddField(
            model_name='metaaction',
            name='target_model',
            field=models.ForeignKey(blank=True, help_text='Dynamic model contextual to this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='meta_engine.metamodel', verbose_name='Target Model'),
        ),
        migrations.CreateModel(
            name='MetaReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g. 'Tax Invoice PDF', 'Picking Slip').", max_length=150, verbose_name='Report Name')),
                ('slug', models.CharField(db_index=True, help_text="Programmatic identifier for print dispatch (e.g. 'invoice_standard').", max_length=100, unique=True, verbose_name='Report Slug')),
                ('report_type', models.CharField(choices=[('pdf', 'Vector PDF Document'), ('html', 'Interactive HTML Report')], default='pdf', help_text='Output document format.', max_length=10, verbose_name='Format')),
                ('paper_format', models.CharField(choices=[('A4', 'Standard A4 (210 × 297 mm)'), ('Letter', 'US Letter (8.5 × 11 in)'), ('thermal_80mm', 'Thermal Receipt (80 mm)')], default='A4', help_text='Target paper standard.', max_length=20, verbose_name='Paper Size')),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='Page printing orientation.', max_length=20, verbose_name='Orientation')),
                ('template_dsl', models.TextField(blank=True, default='', help_text='HTML/CSS markup with CSS Paged Media rules and {{record.field}} placeholders.', verbose_name='Template Markup (HTML/CSS)')),
                ('layout_schema', models.JSONField(blank=True, default=dict, help_text='Coordinate schema tree for drag-and-drop report builders.', verbose_name='Visual Coordinates')),
                ('is_default', models.BooleanField(default=False, help_text='Primary report format triggered by default print button.', verbose_name='Is Default Report')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('model', models.ForeignKey(help_text='Dynamic model generating data for this report.', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='meta_engine.metamodel', verbose_name='Target Model')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Metadata Report',
                'verbose_name_plural': 'Metadata Reports',
                'ordering': ['model__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetaRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the security rule.', max_length=150, verbose_name='Rule Name')),
                ('perm_read', models.BooleanField(default=True, verbose_name='Allow Read')),
                ('perm_write', models.BooleanField(default=True, verbose_name='Allow Write')),
                ('perm_create', models.BooleanField(default=True, verbose_name='Allow Create')),
                ('perm_delete', models.BooleanField(default=False, verbose_name='Allow Delete')),
                ('domain_filter', models.JSONField(blank=True, default=dict, help_text="Contextual domain expression (e.g. {'created_by': '{{user.id}}'}).", verbose_name='Row-Level Access Filter')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('group', models.ForeignKey(blank=True, help_text='Leave empty to apply to all authenticated users.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_rules', to='auth.group', verbose_name='Target User Group')),
                ('model', models.ForeignKey(help_text='Dynamic model governed by this access policy.', on_delete=django.db.models.deletion.CASCADE, related_name='security_rules', to='meta_engine.metamodel', verbose_name='Target Model')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Metadata Security Rule',
                'verbose_name_plural': 'Metadata Security Rules',
                'ordering': ['model__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MetaView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the view (e.g. 'Primary Form', 'Sales Pipeline Kanban').", max_length=150, verbose_name='View Title')),
                ('view_type', models.CharField(choices=[('form', 'Form / Detail View'), ('list', 'List / Table View'), ('kanban', 'Kanban Card Board'), ('pivot', 'Pivot / Aggregation Table'), ('tree', 'Hierarchical Tree')], default='form', help_text='Visual presentation format.', max_length=20, verbose_name='View Type')),
                ('is_default', models.BooleanField(default=False, help_text='Primary view opened when viewing this model.', verbose_name='Is Default View')),
                ('layout_schema', models.JSONField(blank=True, default=dict, help_text='Structured JSON layout specification (tabs, sections, columns, widgets).', verbose_name='Declarative Layout Schema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('model', models.ForeignKey(help_text='Dynamic model displayed by this view.', on_delete=django.db.models.deletion.CASCADE, related_name='views', to='meta_engine.metamodel', verbose_name='Model')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Metadata View',
                'verbose_name_plural': 'Metadata Views',
                'ordering': ['model__name', 'view_type', '-is_default'],
            },
        ),
        migrations.AddField(
            model_name='metaaction',
            name='target_view',
            field=models.ForeignKey(blank=True, help_text='Specific layout view opened by window action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_actions', to='meta_engine.metaview', verbose_name='Target View'),
        ),
        migrations.CreateModel(
            name='MetaField',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Physical database column name (e.g. 'email', 'phone', 'company_id').", max_length=100, verbose_name='Field Name')),
                ('label', models.CharField(help_text='User-facing label for forms and tables.', max_length=150, verbose_name='Display Label')),
                ('field_type', models.CharField(choices=[('char', 'Text (Single-line)'), ('text', 'Text (Multi-line)'), ('integer', 'Integer Number'), ('float', 'Floating-Point Number'), ('decimal', 'Precise Decimal / Currency'), ('boolean', 'Boolean Flag (Yes/No)'), ('date', 'Date'), ('datetime', 'Date & Timestamp'), ('json', 'JSON / Structured Data'), ('foreign_key', 'Relational Link (Foreign Key)'), ('many_to_many', 'Many-to-Many Relationship'), ('file', 'File / Media Attachment')], default='char', help_text='Relational or scalar data type.', max_length=30, verbose_name='Data Type')),
                ('max_length', models.PositiveIntegerField(blank=True, default=255, help_text='Maximum character length for text fields.', null=True, verbose_name='Max Length')),
                ('max_digits', models.PositiveSmallIntegerField(blank=True, default=12, help_text='Maximum number of digits for precise decimal numbers.', null=True, verbose_name='Max Digits')),
                ('decimal_places', models.PositiveSmallIntegerField(blank=True, default=2, help_text='Number of decimal places for currency or percentages.', null=True, verbose_name='Decimal Places')),
                ('required', models.BooleanField(default=False, help_text='If checked, null or blank values are rejected on save.', verbose_name='Required')),
                ('unique', models.BooleanField(default=False, help_text='Enforces a unique database constraint on this column.', verbose_name='Unique')),
                ('index', models.BooleanField(default=False, help_text='Creates a PostgreSQL B-Tree index on this column for fast searching.', verbose_name='Indexed')),
                ('default_value', models.CharField(blank=True, default='', help_text='Raw default value assigned when no input is provided.', max_length=255, verbose_name='Default Value')),
                ('choices', models.JSONField(blank=True, default=list, help_text="JSON list of allowed options: [{'value': 'draft', 'label': 'Draft'}].", verbose_name='Allowed Choices')),
                ('fk_target_app_model', models.CharField(blank=True, default='', help_text="Target static Django model if pointing to kernel models (e.g. 'auth.User').", max_length=150, verbose_name='Foreign Key Static Target')),
                ('on_delete_behavior', models.CharField(choices=[('CASCADE', 'Cascade (Delete dependent records)'), ('SET_NULL', 'Set Null (Keep record, clear reference)'), ('PROTECT', 'Protect (Block deletion if referenced)'), ('RESTRICT', 'Restrict (Standard relational restriction)')], default='SET_NULL', help_text='Relational cascade behavior on target deletion.', max_length=20, verbose_name='On Delete Behavior')),
                ('help_text', models.TextField(blank=True, help_text='Explanatory tooltip displayed in UI forms.', verbose_name='Field Help Text')),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Display sequence for automatic form layout generation.', verbose_name='Sequence Order')),
                ('is_system', models.BooleanField(default=False, help_text='System fields cannot be altered or removed.', verbose_name='Is System Protected')),
                ('is_readonly', models.BooleanField(default=False, help_text='Field value cannot be edited directly by users in UI forms.', verbose_name='Read-Only')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('fk_target_model', models.ForeignKey(blank=True, help_text='Target dynamic MetaModel if field_type is foreign_key or many_to_many.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencing_fields', to='meta_engine.metamodel', verbose_name='Foreign Key Dynamic Target')),
                ('model', models.ForeignKey(help_text='Parent metadata model that owns this field.', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='meta_engine.metamodel', verbose_name='Target Model')),
            ],
            options={
                'verbose_name': 'Metadata Field',
                'verbose_name_plural': 'Metadata Fields',
                'ordering': ['sequence', 'name'],
                'unique_together': {('model', 'name')},
            },
        ),
    ]
