# Generated by Django 5.1.15 on 2026-09-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metamodel',
            name='table_name',
            field=models.CharField(blank=True, db_index=True, help_text="Physical PostgreSQL table name (e.g. 'app_contacts_partner').", max_length=120, unique=True, verbose_name='Database Table Name'),
        ),
    ]
