# Generated by Django 5.1.15 on 2026-09-09 15:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_engine', '0002_alter_metamodel_table_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(db_index=True, help_text="Unique identifier/slug for the app package (e.g. 'crm', 'contacts').", max_length=100, unique=True, verbose_name='Module Identifier')),
                ('name', models.CharField(help_text="Human-readable title (e.g. 'Customer Relationship Management').", max_length=150, verbose_name='Module Name')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='Version')),
                ('category', models.CharField(default='General', help_text="Business category (e.g. 'Sales', 'Operations', 'Finance', 'Productivity').", max_length=100, verbose_name='Category')),
                ('icon', models.CharField(default='box', help_text="Icon identifier (e.g. 'users', 'briefcase', 'database').", max_length=100, verbose_name='Icon')),
                ('summary', models.CharField(blank=True, help_text='Short one-sentence summary.', max_length=255, verbose_name='Summary')),
                ('description', models.TextField(blank=True, help_text='Full description of the module capabilities.', verbose_name='Description')),
                ('author', models.CharField(default='System', max_length=150, verbose_name='Author')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='Website / Repo')),
                ('license', models.CharField(default='MIT', max_length=50, verbose_name='License')),
                ('status', models.CharField(choices=[('uninstalled', 'Not Installed'), ('installed', 'Installed'), ('to_upgrade', 'Upgrade Available'), ('error', 'Installation / Runtime Error')], db_index=True, default='uninstalled', max_length=30, verbose_name='Status')),
                ('dependencies', models.JSONField(blank=True, default=list, help_text='List of app_ids required by this module.', verbose_name='Dependencies')),
                ('manifest_data', models.JSONField(blank=True, default=dict, help_text='Full cached manifest payload.', verbose_name='Manifest Data')),
                ('installed_at', models.DateTimeField(blank=True, null=True, verbose_name='Installed At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'System Module',
                'verbose_name_plural': 'System Modules',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='metaaction',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='meta_engine.systemmodule', verbose_name='Parent Module'),
        ),
        migrations.AddField(
            model_name='metamenu',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='meta_engine.systemmodule', verbose_name='Parent Module'),
        ),
        migrations.AddField(
            model_name='metamodel',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Modular app package that introduced this metadata definition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='meta_engine.systemmodule', verbose_name='Parent Module'),
        ),
        migrations.AddField(
            model_name='metareport',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='meta_engine.systemmodule', verbose_name='Parent Module'),
        ),
        migrations.AddField(
            model_name='metarule',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules', to='meta_engine.systemmodule', verbose_name='Parent Module'),
        ),
        migrations.AddField(
            model_name='metaview',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='meta_engine.systemmodule', verbose_name='Parent Module'),
        ),
    ]
