# Generated by Django 5.1.15 on 2026-09-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_engine', '0003_systemmodule_metaaction_module_metamenu_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metamodel',
            name='is_tenant_aware',
            field=models.BooleanField(db_index=True, default=True, help_text='Enforces row-level multi-tenant isolation scoped to an Organization/Workspace.', verbose_name='Is Tenant Aware'),
        ),
    ]
