# Generated by Django 5.1.15 on 2026-09-09 17:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Receive notifications in system dashboard.', verbose_name='In-App Enabled')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive email notifications for important alerts.', verbose_name='Email Enabled')),
                ('webhook_enabled', models.BooleanField(default=False, help_text='Dispatch HTTP POST payload to external webhook URL.', verbose_name='Webhook Enabled')),
                ('slack_enabled', models.BooleanField(default=False, help_text='Dispatch alerts to Slack incoming webhook URL.', verbose_name='Slack Alerts Enabled')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Webhook Endpoint URL')),
                ('slack_webhook_url', models.URLField(blank=True, default='', max_length=512, verbose_name='Slack Incoming Webhook URL')),
                ('channel_config', models.JSONField(blank=True, default=dict, help_text='Custom channel metadata (e.g. min level thresholds).', verbose_name='Channel Configurations')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=16, verbose_name='Notification Level')),
                ('title', models.CharField(help_text='Brief notification title or summary.', max_length=255, verbose_name='Title')),
                ('message', models.TextField(help_text='Full text body of the notification.', verbose_name='Message Content')),
                ('action_url', models.CharField(blank=True, default='', help_text='Optional relative or absolute link for interactive navigation.', max_length=512, verbose_name='Action URL')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when recipient marked this notification as read.', null=True, verbose_name='Read At')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Indicates if the notification has been read.', verbose_name='Is Read')),
                ('channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('webhook', 'HTTP Webhook'), ('slack', 'Slack Alert'), ('hermes', 'Hermes AI Agent')], db_index=True, default='in_app', max_length=32, verbose_name='Delivery Channel')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Structured JSON payload context (e.g. task_id, audit_id).', verbose_name='Extra Data')),
                ('actor', models.ForeignKey(blank=True, help_text='User or bot profile that triggered this notification (null if system).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Actor / Sender')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization / workspace owning this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='Organization')),
                ('recipient', models.ForeignKey(help_text='Target user receiving this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'), models.Index(fields=['organization', 'recipient', 'is_read'], name='notificatio_organiz_5cc15d_idx')],
            },
        ),
    ]
