# Generated by Django 5.1.15 on 2026-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('app_label', models.CharField(db_index=True, help_text="Application identifier (e.g. 'automation', 'integration', 'general').", max_length=100, verbose_name='App Label')),
                ('key', models.CharField(db_index=True, help_text='Unique parameter key within the application group.', max_length=100, verbose_name='Setting Key')),
                ('raw_value', models.TextField(blank=True, default='', help_text='Serialized or encrypted value stored in the database.', verbose_name='Raw Stored Value')),
                ('data_type', models.CharField(default='str', help_text='Data type matching the registered Setting definition.', max_length=20, verbose_name='Data Type')),
            ],
            options={
                'verbose_name': 'Application Setting Value',
                'verbose_name_plural': 'Application Setting Values',
                'indexes': [models.Index(fields=['app_label', 'key'], name='core_appset_app_lab_f520ab_idx')],
                'unique_together': {('app_label', 'key')},
            },
        ),
    ]
