"""Fixtures and bootstrapping for Reporting Module."""

import logging
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from modules.base.identity_rbac.models import Company
from modules.base.reporting.models import ReportTemplate
from modules.base.reporting.registry import report_registry
from modules.base.reporting.reports.storage_audit_report import StorageAuditReport
from modules.base.reporting.reports.user_directory_report import UserDirectoryReport

logger = logging.getLogger("sovereign.reporting.fixtures")


def register_standard_reports():
    """Register all built-in Python report classes into the global ReportRegistry."""
    report_registry.register(StorageAuditReport)
    report_registry.register(UserDirectoryReport)
    logger.info("Bootstrap: Registered standard domain reports into ReportRegistry")


async def seed_default_report_templates(db: AsyncSession):
    """Seed default company ReportTemplate records idempotently."""
    stmt = select(Company).where(Company.deleted_at.is_(None))
    companies = (await db.execute(stmt)).scalars().all()

    for comp in companies:
        # Check if default template already exists for company
        chk_stmt = select(ReportTemplate).where(
            ReportTemplate.company_id == comp.id,
            ReportTemplate.code == "standard_clean",
        )
        existing = (await db.execute(chk_stmt)).scalar_one_or_none()

        if not existing:
            default_template = ReportTemplate(
                company_id=comp.id,
                name="Standard Clean Executive Layout",
                code="standard_clean",
                orientation="portrait",
                primary_color="#1E3A8A",
                show_company_logo=True,
                show_page_numbers=True,
                header_text=f"Official Report • {comp.name}",
                footer_text="Generated by Sovereign Enterprise Platform • Confidential",
                is_default=True,
                description="Default executive clean layout suitable for all business documents and tabular audits.",
            )
            db.add(default_template)
            logger.info(f"Seeded default report template 'standard_clean' for company '{comp.name}'")

    await db.commit()
