/**
 * Navigation Menu API Client & Fallback Fixtures.
 */

import { MenuItemNode } from '../types/menus';

export const DEFAULT_FALLBACK_MENUS: MenuItemNode[] = [
  {
    id: '10000000-0000-0000-0000-000000000001',
    code: 'sales.root',
    name: 'Sales',
    module_name: 'sales',
    icon: 'trending-up',
    sequence: 10,
    action_type: 'folder',
    default_view: 'list',
    route_path: '/sales',
    is_system: true,
    is_active: true,
    children: [
      {
        id: '10000000-0000-0000-0000-000000000010',
        code: 'sales.orders_cat',
        name: 'Orders',
        module_name: 'sales',
        sequence: 10,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '10000000-0000-0000-0000-000000000011',
            code: 'sales.quotations',
            name: 'Quotations',
            module_name: 'sales',
            sequence: 10,
            action_type: 'window',
            res_model: 'SaleOrder',
            default_view: 'list',
            domain_filter: { state: 'draft' },
            route_path: '/sales/quotations',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '10000000-0000-0000-0000-000000000012',
            code: 'sales.orders',
            name: 'Orders',
            module_name: 'sales',
            sequence: 20,
            action_type: 'window',
            res_model: 'SaleOrder',
            default_view: 'list',
            domain_filter: { state: 'sale' },
            route_path: '/sales/orders',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '10000000-0000-0000-0000-000000000013',
            code: 'sales.customers',
            name: 'Customers',
            module_name: 'sales',
            sequence: 30,
            action_type: 'window',
            res_model: 'Party',
            default_view: 'list',
            domain_filter: { is_customer: true },
            route_path: '/sales/customers',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
      {
        id: '10000000-0000-0000-0000-000000000020',
        code: 'sales.products_cat',
        name: 'Products',
        module_name: 'sales',
        sequence: 20,
        action_type: 'folder',
        default_view: 'kanban',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '10000000-0000-0000-0000-000000000021',
            code: 'sales.products',
            name: 'Products',
            module_name: 'sales',
            sequence: 10,
            action_type: 'window',
            res_model: 'Product',
            default_view: 'kanban',
            route_path: '/sales/products',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
      {
        id: '10000000-0000-0000-0000-000000000030',
        code: 'sales.reporting_cat',
        name: 'Reporting',
        module_name: 'sales',
        sequence: 30,
        action_type: 'folder',
        default_view: 'pivot',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '10000000-0000-0000-0000-000000000031',
            code: 'sales.report_sales',
            name: 'Sales Analysis',
            module_name: 'sales',
            sequence: 10,
            action_type: 'report',
            res_model: 'SaleOrder',
            default_view: 'pivot',
            route_path: '/sales/reporting',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: '20000000-0000-0000-0000-000000000001',
    code: 'purchases.root',
    name: 'Purchases',
    module_name: 'purchases',
    icon: 'shopping-cart',
    sequence: 20,
    action_type: 'folder',
    default_view: 'list',
    route_path: '/purchases',
    is_system: true,
    is_active: true,
    children: [
      {
        id: '20000000-0000-0000-0000-000000000010',
        code: 'purchases.orders_cat',
        name: 'Orders',
        module_name: 'purchases',
        sequence: 10,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '20000000-0000-0000-0000-000000000011',
            code: 'purchases.rfq',
            name: 'Requests for Quotation',
            module_name: 'purchases',
            sequence: 10,
            action_type: 'window',
            res_model: 'PurchaseOrder',
            default_view: 'list',
            domain_filter: { state: 'draft' },
            route_path: '/purchases/rfq',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '20000000-0000-0000-0000-000000000012',
            code: 'purchases.purchase_orders',
            name: 'Purchase Orders',
            module_name: 'purchases',
            sequence: 20,
            action_type: 'window',
            res_model: 'PurchaseOrder',
            default_view: 'list',
            domain_filter: { state: 'purchase' },
            route_path: '/purchases/orders',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '20000000-0000-0000-0000-000000000013',
            code: 'purchases.vendors',
            name: 'Vendors',
            module_name: 'purchases',
            sequence: 30,
            action_type: 'window',
            res_model: 'Party',
            default_view: 'list',
            domain_filter: { is_supplier: true },
            route_path: '/purchases/vendors',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
      {
        id: '20000000-0000-0000-0000-000000000020',
        code: 'purchases.products_cat',
        name: 'Products',
        module_name: 'purchases',
        sequence: 20,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '20000000-0000-0000-0000-000000000021',
            code: 'purchases.products',
            name: 'Products',
            module_name: 'purchases',
            sequence: 10,
            action_type: 'window',
            res_model: 'Product',
            default_view: 'list',
            route_path: '/purchases/products',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: '30000000-0000-0000-0000-000000000001',
    code: 'accounting.root',
    name: 'Accounting',
    module_name: 'accounting',
    icon: 'book-open',
    sequence: 30,
    action_type: 'folder',
    default_view: 'list',
    route_path: '/accounting',
    is_system: true,
    is_active: true,
    children: [
      {
        id: '30000000-0000-0000-0000-000000000010',
        code: 'accounting.customers_cat',
        name: 'Customers',
        module_name: 'accounting',
        sequence: 10,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '30000000-0000-0000-0000-000000000011',
            code: 'accounting.invoices',
            name: 'Invoices',
            module_name: 'accounting',
            sequence: 10,
            action_type: 'window',
            res_model: 'AccountMove',
            default_view: 'list',
            domain_filter: { move_type: 'out_invoice' },
            route_path: '/accounting/invoices',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '30000000-0000-0000-0000-000000000012',
            code: 'accounting.credit_notes',
            name: 'Credit Notes',
            module_name: 'accounting',
            sequence: 20,
            action_type: 'window',
            res_model: 'AccountMove',
            default_view: 'list',
            domain_filter: { move_type: 'out_refund' },
            route_path: '/accounting/credit-notes',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
      {
        id: '30000000-0000-0000-0000-000000000020',
        code: 'accounting.vendors_cat',
        name: 'Vendors',
        module_name: 'accounting',
        sequence: 20,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '30000000-0000-0000-0000-000000000021',
            code: 'accounting.bills',
            name: 'Bills',
            module_name: 'accounting',
            sequence: 10,
            action_type: 'window',
            res_model: 'AccountMove',
            default_view: 'list',
            domain_filter: { move_type: 'in_invoice' },
            route_path: '/accounting/bills',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '30000000-0000-0000-0000-000000000022',
            code: 'accounting.refunds',
            name: 'Refunds',
            module_name: 'accounting',
            sequence: 20,
            action_type: 'window',
            res_model: 'AccountMove',
            default_view: 'list',
            domain_filter: { move_type: 'in_refund' },
            route_path: '/accounting/refunds',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
      {
        id: '30000000-0000-0000-0000-000000000030',
        code: 'accounting.accounting_cat',
        name: 'Accounting',
        module_name: 'accounting',
        sequence: 30,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '30000000-0000-0000-0000-000000000031',
            code: 'accounting.journal_entries',
            name: 'Journal Entries',
            module_name: 'accounting',
            sequence: 10,
            action_type: 'window',
            res_model: 'AccountMove',
            default_view: 'list',
            domain_filter: { move_type: 'entry' },
            route_path: '/accounting/journal-entries',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '30000000-0000-0000-0000-000000000032',
            code: 'accounting.chart_of_accounts',
            name: 'Chart of Accounts',
            module_name: 'accounting',
            sequence: 20,
            action_type: 'window',
            res_model: 'Account',
            default_view: 'list',
            route_path: '/accounting/chart-of-accounts',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
      {
        id: '30000000-0000-0000-0000-000000000040',
        code: 'accounting.reporting_cat',
        name: 'Reporting',
        module_name: 'accounting',
        sequence: 40,
        action_type: 'folder',
        default_view: 'pivot',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '30000000-0000-0000-0000-000000000041',
            code: 'accounting.trial_balance',
            name: 'Trial Balance',
            module_name: 'accounting',
            sequence: 10,
            action_type: 'report',
            res_model: 'AccountMove',
            default_view: 'pivot',
            route_path: '/accounting/trial-balance',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '30000000-0000-0000-0000-000000000042',
            code: 'accounting.profit_and_loss',
            name: 'Profit and Loss',
            module_name: 'accounting',
            sequence: 20,
            action_type: 'report',
            res_model: 'AccountMove',
            default_view: 'pivot',
            route_path: '/accounting/profit-loss',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '30000000-0000-0000-0000-000000000043',
            code: 'accounting.balance_sheet',
            name: 'Balance Sheet',
            module_name: 'accounting',
            sequence: 30,
            action_type: 'report',
            res_model: 'AccountMove',
            default_view: 'pivot',
            route_path: '/accounting/balance-sheet',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: '40000000-0000-0000-0000-000000000001',
    code: 'settings.root',
    name: 'Settings',
    module_name: 'settings',
    icon: 'settings',
    sequence: 100,
    action_type: 'folder',
    default_view: 'list',
    route_path: '/settings',
    is_system: true,
    is_active: true,
    children: [
      {
        id: '40000000-0000-0000-0000-000000000010',
        code: 'settings.general_cat',
        name: 'General',
        module_name: 'settings',
        sequence: 10,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '40000000-0000-0000-0000-000000000011',
            code: 'settings.general',
            name: 'General Settings',
            module_name: 'settings',
            sequence: 10,
            action_type: 'settings',
            default_view: 'form',
            route_path: '/settings/general',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '40000000-0000-0000-0000-000000000012',
            code: 'settings.users',
            name: 'Users & Roles',
            module_name: 'settings',
            sequence: 20,
            action_type: 'window',
            res_model: 'User',
            default_view: 'list',
            route_path: '/settings/users',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '40000000-0000-0000-0000-000000000013',
            code: 'settings.companies',
            name: 'Companies',
            module_name: 'settings',
            sequence: 30,
            action_type: 'window',
            res_model: 'Company',
            default_view: 'list',
            route_path: '/settings/companies',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
      {
        id: '40000000-0000-0000-0000-000000000020',
        code: 'settings.customization_cat',
        name: 'Customization',
        module_name: 'settings',
        sequence: 20,
        action_type: 'folder',
        default_view: 'list',
        is_system: true,
        is_active: true,
        children: [
          {
            id: '40000000-0000-0000-0000-000000000021',
            code: 'settings.menus',
            name: 'Menu Editor',
            module_name: 'settings',
            sequence: 10,
            action_type: 'window',
            res_model: 'MenuItem',
            default_view: 'list',
            route_path: '/settings/menus',
            is_system: true,
            is_active: true,
            children: [],
          },
          {
            id: '40000000-0000-0000-0000-000000000022',
            code: 'settings.views',
            name: 'Views Studio',
            module_name: 'settings',
            sequence: 20,
            action_type: 'window',
            res_model: 'ViewDefinition',
            default_view: 'list',
            route_path: '/settings/views',
            is_system: true,
            is_active: true,
            children: [],
          },
        ],
      },
    ],
  },
];

/**
 * Fetch hierarchical navigation menus from backend API with transparent fallback.
 */
export async function fetchUserMenus(token?: string, companyId?: string): Promise<{ data: MenuItemNode[]; isLive: boolean }> {
  try {
    const headers: Record<string, string> = {
      'Accept': 'application/json',
    };
    if (token) {
      headers['Authorization'] = `Bearer ${token}`;
    }
    if (companyId) {
      headers['X-Company-ID'] = companyId;
    }

    const res = await fetch('/api/v1/ui/menus', { headers });
    if (res.ok) {
      const data: MenuItemNode[] = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        return { data, isLive: true };
      }
    }
  } catch (err) {
    console.warn('[MenuAPI] Failed fetching live menus from backend, falling back to system defaults:', err);
  }

  return { data: DEFAULT_FALLBACK_MENUS, isLive: false };
}
