# Generated by Django 5.1.15 on 2026-09-09 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_type', models.CharField(choices=[('user', 'Human User'), ('bot', 'Bot Service Account'), ('system', 'System / Background Process'), ('anonymous', 'Anonymous / Unauthenticated')], db_index=True, default='user', max_length=32, verbose_name='Actor Type')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete (Soft)'), ('restore', 'Restore'), ('hard_delete', 'Hard Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('export', 'Export'), ('custom', 'Custom Action')], db_index=True, max_length=64, verbose_name='Action')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], db_index=True, default='success', max_length=32, verbose_name='Status')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Object ID')),
                ('object_repr', models.CharField(blank=True, help_text='Human-readable title or label of target object at time of event.', max_length=255, verbose_name='Target Representation')),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Structured diff: {'field_name': {'old': v1, 'new': v2}}.", verbose_name='Attribute Changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Request Correlation ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra telemetry or contextual parameters.', verbose_name='Context Metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('actor', models.ForeignKey(blank=True, help_text='The user or service account performing the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('organization', models.ForeignKey(blank=True, help_text='Associated workspace / tenant (null for system-level actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='tenants.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action', '-timestamp'], name='idx_audit_action_ts'), models.Index(fields=['organization', '-timestamp'], name='idx_audit_org_ts'), models.Index(fields=['actor', '-timestamp'], name='idx_audit_actor_ts'), models.Index(fields=['content_type', 'object_id'], name='idx_audit_target')],
            },
        ),
    ]
