# Generated by Django 5.1.15 on 2026-09-08 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Hermes profile slug (e.g., cost_controller)', max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('orchestrator', 'Orchestrator / Chief of Staff'), ('finance', 'Finance & Cost Control'), ('quality_assurance', 'Quality Assurance & Audit'), ('communications', 'Communications & Client Relations'), ('knowledge_management', 'Knowledge Management & Documentation'), ('general', 'General / Custom')], default='general', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(default='google/gemini-2.5-flash', max_length=120)),
                ('provider', models.CharField(default='openrouter', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='agenttask',
            name='cost_usd',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='review_verdict',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('changes_requested', 'Changes Requested')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='reviewer_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('review', 'In Review'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='assigned_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='integration.agentprofile'),
        ),
        migrations.CreateModel(
            name='SpendReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported_by', models.CharField(default='cost_controller', max_length=64)),
                ('total_api_calls', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveBigIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('daily_budget_usd', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
                ('budget_status', models.CharField(choices=[('OK', 'Within Budget'), ('WARNING', 'Approaching Limit'), ('EXCEEDED', 'Budget Exceeded')], default='OK', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_reports', to='integration.agentprofile')),
            ],
            options={
                'verbose_name': 'Spend Report',
                'verbose_name_plural': 'Spend Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
