# Generated by Django 5.1.15 on 2026-09-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_agentprofile_agenttask_cost_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='reasoning_effort',
            field=models.CharField(choices=[('none', 'None (Disabled)'), ('low', 'Low (Fast / Minimal Cost)'), ('medium', 'Medium (Balanced Default)'), ('high', 'High (Deep Reasoning / Strict QA)'), ('max', 'Max (Frontier Reasoning Budget)')], default='medium', help_text='Reasoning/thinking effort level passed to Hermes Agent runtime (none, low, medium, high, max).', max_length=20),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='reasoning_effort',
            field=models.CharField(choices=[('none', 'None (Disabled)'), ('low', 'Low (Fast / Minimal Cost)'), ('medium', 'Medium (Balanced Default)'), ('high', 'High (Deep Reasoning / Strict QA)'), ('max', 'Max (Frontier Reasoning Budget)'), ('inherit', 'Inherit from Profile')], default='inherit', help_text='Task-specific reasoning effort override, or inherit from profile.', max_length=20),
        ),
    ]
