# Generated by Django 5.1.15 on 2026-09-09 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_agentprofile_reasoning_effort_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Underlying Django service account / bot user for RBAC and API authentication.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User/bot account that created this task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spendreport',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User/bot account that submitted this spend report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spend_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
