# Generated by Django 5.1.15 on 2026-09-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_unified_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('orchestrator', 'Orchestrator / Chief of Staff'), ('finance', 'Finance & Cost Control'), ('quality_assurance', 'Quality Assurance & Audit'), ('communications', 'Communications & Client Relations'), ('knowledge_management', 'Knowledge Management & Documentation'), ('general', 'General / Custom')], default='general', max_length=60),
        ),
    ]
