# Generated by Django 5.1.15 on 2026-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_alter_profile_display_name_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية')], default='en', help_text='User interface language preference (en / ar).', max_length=10),
        ),
    ]
