# Generated by Django 5.1.15 on 2026-09-11 02:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_agenttask_updated_by_handshakelog_updated_at_and_more'),
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display label for this credential (e.g., 'Primary OpenRouter', 'Gemini Flash Tier').", max_length=100)),
                ('provider_type', models.CharField(choices=[('openrouter', 'OpenRouter'), ('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('groq', 'Groq'), ('deepseek', 'DeepSeek'), ('custom', 'Custom / OpenAI-Compatible Endpoint')], db_index=True, default='openrouter', help_text='Underlying LLM provider service.', max_length=50)),
                ('encrypted_api_key', models.TextField(blank=True, default='', help_text='Encrypted API key stored securely at rest.')),
                ('base_url', models.URLField(blank=True, default='', help_text='Optional custom API base URL (e.g. https://openrouter.ai/api/v1, or local Ollama/vLLM).', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this provider credential can be used for inference.')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Designates this credential as the default for its provider type.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Custom provider parameters, default headers, or rate limits.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='Optional workspace scoping for multi-tenant isolation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_credentials', to='tenants.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Provider Credential',
                'verbose_name_plural': 'Provider Credentials',
                'ordering': ['provider_type', '-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='provider_credential',
            field=models.ForeignKey(blank=True, help_text='Optional dedicated provider credential assigned to this profile.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='integration.providercredential'),
        ),
    ]
