# Generated by Django 5.1.15 on 2026-09-11 07:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_providercredential_profile_provider_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='spendreport',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='Cost efficiency and model optimization recommendations generated during spend audit.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='provider_credential',
            field=models.ForeignKey(blank=True, help_text='Optional override: Leave blank to automatically use the default credential for the selected provider. Specify only for dedicated keys or custom endpoints (e.g. Ollama/vLLM).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='integration.providercredential'),
        ),
        migrations.CreateModel(
            name='ModelBenchmark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_identifier', models.CharField(db_index=True, help_text='Full model identifier (e.g. google/gemini-2.5-flash, anthropic/claude-3-5-sonnet).', max_length=120)),
                ('benchmark_name', models.CharField(db_index=True, default='DeepSWE', help_text='Name of benchmark suite (e.g. DeepSWE, SWE-bench).', max_length=60)),
                ('score', models.FloatField(help_text='Primary benchmark pass rate / score percentage (0.0 - 100.0).')),
                ('avg_cost_per_task', models.DecimalField(blank=True, decimal_places=4, help_text='Measured average cost per benchmark task in USD.', max_digits=10, null=True)),
                ('tokens_per_task', models.PositiveIntegerField(blank=True, help_text='Average output or total tokens per task.', null=True)),
                ('agent_steps', models.PositiveIntegerField(blank=True, help_text='Average agent reasoning/tool steps per task.', null=True)),
                ('source_url', models.URLField(blank=True, default='https://deepswe.datacurve.ai/', help_text='Origin leaderboard or reference URL.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional benchmark dimensions (context window, framework, raw metrics).')),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Timestamp when benchmark record was last updated.')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Model Benchmark',
                'verbose_name_plural': 'Model Benchmarks',
                'ordering': ['-score', 'avg_cost_per_task'],
                'unique_together': {('model_identifier', 'benchmark_name')},
            },
        ),
    ]
