# Generated by Django 5.1.15 on 2026-09-11 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0010_spendreport_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_budget_usd',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Allocated AI assistance dollar budget for this client engagement.', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_spend_usd',
            field=models.DecimalField(decimal_places=4, default=0.0, help_text='Cumulative LLM spend consumed by this client in USD.', max_digits=10),
        ),
        migrations.AddField(
            model_name='spendreport',
            name='client_profile',
            field=models.ForeignKey(blank=True, help_text='Optional client profile associated with this spend report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_spend_reports', to='integration.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('orchestrator', 'Orchestrator / Chief of Staff'), ('finance', 'Finance & Cost Control'), ('quality_assurance', 'Quality Assurance & Audit'), ('communications', 'Client Service & Communications'), ('knowledge_management', 'Knowledge Management & Documentation'), ('general', 'General / Custom')], default='general', max_length=60),
        ),
    ]
