# Generated by Django 5.1.15 on 2026-09-11 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('integration', '0011_profile_ai_budget_usd_profile_ai_spend_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The client company/account this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='clients.client'),
        ),
        migrations.AddField(
            model_name='spendreport',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional client entity associated with this spend report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spend_reports', to='clients.client'),
        ),
    ]
