# Generated by Django 5.1.15 on 2026-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0012_profile_client_spendreport_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('orchestrator', 'Orchestrator / Chief of Staff'), ('finance', 'Finance & Cost Control'), ('quality_assurance', 'Quality Assurance & Audit'), ('communications', 'Client Service & Communications'), ('security', 'Security & Access Control (SecOps)'), ('knowledge_management', 'Knowledge Management & Documentation'), ('general', 'General / Custom')], default='general', max_length=60),
        ),
    ]
