# Generated by Django 5.1.15 on 2026-09-09 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique descriptive name for the automation rule.', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed purpose and behavior notes.')),
                ('is_active', models.BooleanField(default=True, help_text='Active toggle: uncheck to pause this rule without deleting it.')),
                ('trigger_type', models.CharField(choices=[('model_event', '📦 Model Event (CRUD)'), ('time_based', '⏱️ Time-Based Schedule'), ('webhook', '🌐 Inbound Webhook'), ('manual', '▶️ Manual Only')], default='model_event', help_text='Whether this rule fires on database events, periodic timers, or webhooks.', max_length=50)),
                ('execution_mode', models.CharField(choices=[('recurring', '🔁 Recurring'), ('once', '⚡ Once (One-Shot)')], default='recurring', help_text="'once' automatically deactivates the rule after a single successful run.", max_length=20)),
                ('target_model', models.CharField(blank=True, help_text="Django model to watch, e.g. 'auth.User' or 'integration.AgentTask'.", max_length=150)),
                ('event_type', models.CharField(blank=True, choices=[('created', 'Created (Insert)'), ('updated', 'Updated (Edit)'), ('deleted', 'Deleted'), ('any', 'Any Change')], default='created', help_text='CRUD lifecycle event that triggers the action.', max_length=50)),
                ('filter_conditions', models.JSONField(blank=True, default=dict, help_text="JSON criteria required for trigger match, e.g. {'is_agent': true} or {'status': 'completed'}.")),
                ('schedule_unit', models.CharField(blank=True, choices=[('seconds', 'Seconds'), ('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='minutes', help_text='Time scale unit for periodic executions.', max_length=20)),
                ('schedule_value', models.PositiveIntegerField(blank=True, default=5, help_text='Frequency interval number (e.g. 5 for every 5 minutes).', null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Target timestamp for one-shot scheduled execution.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('action_category', models.CharField(choices=[('hermes_agent', '🤖 Hermes Agent Profile'), ('internal_app', '🐍 Internal Django App Handler'), ('script_service', '📜 Script / System Service'), ('external_webhook', '🌐 Outbound Webhook / API')], default='internal_app', help_text='Category of the target service.', max_length=50)),
                ('action_type', models.CharField(help_text="Identifier of the registered action handler (e.g. 'provision_hermes_profile').", max_length=150)),
                ('action_params', models.JSONField(blank=True, default=dict, help_text='Static parameters or configuration dictionary passed to the action handler.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periodic_task', models.OneToOneField(blank=True, help_text='Linked Celery Beat periodic task instance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rule', to='django_celery_beat.periodictask')),
            ],
            options={
                'verbose_name': 'Automation Rule',
                'verbose_name_plural': 'Automation Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_source', models.CharField(help_text='Contextual description of the event that triggered execution.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_context', models.JSONField(blank=True, default=dict, help_text='Payload / model snapshot at the moment of trigger.')),
                ('output_result', models.JSONField(blank=True, default=dict, help_text='Return data from the executed action.')),
                ('error_message', models.TextField(blank=True, help_text='Exception trace or failure message if execution failed.')),
                ('duration_ms', models.IntegerField(default=0, help_text='Execution duration in milliseconds.')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.automationrule')),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
