# Generated by Django 5.1.15 on 2026-09-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Automation Action', 'verbose_name_plural': 'Automation Actions'},
        ),
        migrations.AddField(
            model_name='automationrule',
            name='previous_value',
            field=models.CharField(blank=True, help_text="Optional previous value before change (e.g. 'review' or 'draft').", max_length=100),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='target_value',
            field=models.CharField(blank=True, help_text="Optional target value after change (e.g. 'completed' or 'approved').", max_length=100),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='trigger_field',
            field=models.CharField(blank=True, help_text="Specific field to monitor for changes (e.g. 'status', 'review_verdict', 'cost_usd').", max_length=100),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='event_type',
            field=models.CharField(blank=True, choices=[('created', 'Created (Insert)'), ('updated', 'Updated (Edit)'), ('field_changed', 'Field Changed / State Transition'), ('deleted', 'Deleted'), ('any', 'Any Change')], default='created', help_text='CRUD lifecycle event that triggers the action.', max_length=50),
        ),
    ]
