# Generated by Django 5.1.15 on 2026-09-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_automationrule_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automationrule',
            old_name='target_model',
            new_name='trigger_model',
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_model',
            field=models.CharField(
                blank=True,
                help_text="Source Django model to watch for events, e.g. 'auth.User' or 'integration.AgentTask'.",
                max_length=150
            ),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='target_model',
            field=models.CharField(
                blank=True,
                help_text="Destination Django model for CRUD record operations, e.g. 'integration.AgentTask'.",
                max_length=150
            ),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='target_operation',
            field=models.CharField(
                blank=True,
                choices=[
                    ('create', '➕ Create New Record'),
                    ('update', '✏️ Update Existing Record'),
                    ('delete', '🗑️ Delete Record'),
                ],
                default='',
                help_text="CRUD operation to execute on the target model ('create', 'update', 'delete').",
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='field_mappings',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Mapping of target model fields to values or context expressions, e.g. {'title': '{{task_title}}'}."
            ),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='condition_rules',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Structured Odoo-style visual filter rules: [{'field': 'status', 'operator': '==', 'value': 'completed'}]."
            ),
        ),
        migrations.AddField(
            model_name='automationrule',
            name='is_system',
            field=models.BooleanField(
                default=False,
                help_text="System-level rule protecting core workflows (Hermes provisioning, audits, QA routing) from deletion."
            ),
        ),
    ]
