# Generated by manual decomposition for Phase 7

import django.db.models.deletion
from django.db import migrations, models


def migrate_rules_to_triggers_and_actions(apps, schema_editor):
    AutomationTrigger = apps.get_model('automation', 'AutomationTrigger')
    AutomationAction = apps.get_model('automation', 'AutomationAction')
    AutomationLog = apps.get_model('automation', 'AutomationLog')

    for trigger in AutomationTrigger.objects.all():
        trigger.last_triggered_at = getattr(trigger, 'last_run_at', None)
        trigger.trigger_count = getattr(trigger, 'run_count', 0)
        trigger.save(update_fields=['last_triggered_at', 'trigger_count'])

        action = AutomationAction.objects.create(
            trigger=trigger,
            name=f"{trigger.name} - Action",
            description=trigger.description or '',
            sequence=10,
            is_active=trigger.is_active,
            is_system=trigger.is_system,
            target_model=getattr(trigger, 'target_model', '') or '',
            target_operation=getattr(trigger, 'target_operation', '') or '',
            field_mappings=getattr(trigger, 'field_mappings', {}) or {},
            action_category=getattr(trigger, 'action_category', 'internal_app') or 'internal_app',
            action_type=getattr(trigger, 'action_type', '') or '',
            action_params=getattr(trigger, 'action_params', {}) or {},
            last_run_at=getattr(trigger, 'last_run_at', None),
            run_count=getattr(trigger, 'run_count', 0),
        )

        AutomationLog.objects.filter(rule_id=trigger.id).update(
            trigger=trigger,
            action=action,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_automationrule_next_gen_actions'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
    ]

    operations = [
        # 1. Rename AutomationRule to AutomationTrigger
        migrations.RenameModel(
            old_name='AutomationRule',
            new_name='AutomationTrigger',
        ),
        migrations.AlterModelOptions(
            name='automationtrigger',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Automation Trigger',
                'verbose_name_plural': 'Automation Triggers',
            },
        ),

        # 2. Add trigger-level metrics and update fields
        migrations.AddField(
            model_name='automationtrigger',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='trigger_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='periodic_task',
            field=models.OneToOneField(
                blank=True,
                help_text='Linked Celery Beat periodic task instance.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='automation_trigger',
                to='django_celery_beat.periodictask'
            ),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed purpose and trigger behavior notes.'),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='execution_mode',
            field=models.CharField(choices=[('recurring', '🔁 Recurring'), ('once', '⚡ Once (One-Shot)')], default='recurring', help_text="'once' automatically deactivates the trigger after a single successful execution pipeline.", max_length=20),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active toggle: uncheck to pause this trigger and its actions without deleting it.'),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System-level trigger protecting core workflows from deletion.'),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='name',
            field=models.CharField(help_text='Unique descriptive name for the trigger event.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='trigger_type',
            field=models.CharField(choices=[('model_event', '📦 Model Event (CRUD)'), ('time_based', '⏱️ Time-Based Schedule'), ('webhook', '🌐 Inbound Webhook'), ('manual', '▶️ Manual Only')], default='model_event', help_text='Whether this trigger fires on database events, periodic timers, or webhooks.', max_length=50),
        ),

        # 3. Create AutomationAction model
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive title of the action step.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed action behavior notes.')),
                ('sequence', models.PositiveIntegerField(default=10, help_text='Execution order among actions attached to the same trigger (e.g. 10, 20, 30).')),
                ('is_active', models.BooleanField(default=True, help_text='Active toggle: uncheck to pause this specific action without deleting it.')),
                ('is_system', models.BooleanField(default=False, help_text='Protected system action that cannot be deleted.')),
                ('target_model', models.CharField(blank=True, help_text="Destination Django model for CRUD record operations, e.g. 'integration.AgentTask'.", max_length=150)),
                ('target_operation', models.CharField(blank=True, choices=[('create', '➕ Create New Record'), ('update', '✏️ Update Existing Record'), ('delete', '🗑️ Delete Record')], default='', help_text="CRUD operation to execute on the target model ('create', 'update', 'delete').", max_length=50)),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text="Mapping of target model fields to values or context expressions, e.g. {'title': '{{task_title}}'}.")),
                ('action_category', models.CharField(choices=[('hermes_agent', '🤖 Hermes Agent Profile'), ('internal_app', '🐍 Internal Django App Handler'), ('script_service', '📜 Script / System Service'), ('external_webhook', '🌐 Outbound Webhook / API')], default='internal_app', help_text='Category of the target service.', max_length=50)),
                ('action_type', models.CharField(blank=True, default='', help_text="Identifier of the registered action handler (e.g. 'provision_hermes_profile').", max_length=150)),
                ('action_params', models.JSONField(blank=True, default=dict, help_text='Static parameters or configuration dictionary passed to the action handler.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.ForeignKey(help_text='Parent trigger event that activates this action.', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automation.automationtrigger')),
            ],
            options={
                'verbose_name': 'Automation Action',
                'verbose_name_plural': 'Automation Actions',
                'ordering': ['sequence', 'created_at'],
            },
        ),

        # 4. Update AutomationLog fields
        migrations.AddField(
            model_name='automationlog',
            name='trigger',
            field=models.ForeignKey(blank=True, help_text='Parent trigger event that initiated execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.automationtrigger'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='action',
            field=models.ForeignKey(blank=True, help_text='Specific action step that was executed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='automation.automationaction'),
        ),
        migrations.AlterField(
            model_name='automationlog',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_logs', to='automation.automationtrigger'),
        ),

        # 5. Data migration
        migrations.RunPython(
            migrate_rules_to_triggers_and_actions,
            reverse_code=migrations.RunPython.noop,
        ),

        # 6. Remove obsolete columns from AutomationTrigger
        migrations.RemoveField(
            model_name='automationtrigger',
            name='target_model',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='target_operation',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='field_mappings',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='action_category',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='action_params',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='last_run_at',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='next_run_at',
        ),
        migrations.RemoveField(
            model_name='automationtrigger',
            name='run_count',
        ),
    ]
