# Generated by Django 5.1.15 on 2026-09-11 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_automationaction_created_by_and_more'),
        ('tenants', '0002_create_default_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Optional workspace tenant for scoped private actions (inherits from trigger if omitted).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_actions', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='stop_on_failure',
            field=models.BooleanField(default=True, help_text='Halt subsequent pipeline steps if this action fails.'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='execution_depth',
            field=models.PositiveIntegerField(default=0, help_text='Recursion depth level of this automation execution.'),
        ),
        migrations.AddField(
            model_name='automationlog',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant workspace context during execution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='tenants.organization'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Optional workspace tenant for scoped private automations (null for global/system triggers).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_triggers', to='tenants.organization'),
        ),
    ]
