# Generated by Django 5.1.15 on 2026-09-11 09:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('name', models.CharField(help_text='Display name of the client company or account (e.g. Acme Corporation).', max_length=255, verbose_name='Client Name')),
                ('slug', models.SlugField(help_text='Unique identifier slug within the organization (e.g. acme-corp).', max_length=100, verbose_name='Client Slug')),
                ('primary_contact_name', models.CharField(blank=True, default='', help_text='Main point of contact at the client organization.', max_length=150, verbose_name='Primary Contact Name')),
                ('primary_contact_email', models.EmailField(blank=True, default='', help_text='Main contact email for correspondence and notifications.', max_length=254, verbose_name='Primary Contact Email')),
                ('primary_contact_phone', models.CharField(blank=True, default='', help_text='Direct telephone or mobile contact.', max_length=50, verbose_name='Primary Contact Phone')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='Operational state of the client account.', max_length=20, verbose_name='Account Status')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal context, SLA specifics, or account preferences.', verbose_name='Administrative Notes')),
                ('is_ai_enabled', models.BooleanField(db_index=True, default=True, help_text='Master entitlement gate. If disabled, client cannot use AI concierge services.', verbose_name='AI Service Enabled')),
                ('ai_budget_usd', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Dollar expenditure ceiling allocated for this client.', max_digits=10, verbose_name='AI Budget (USD)')),
                ('ai_spend_usd', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Real-time dollar cost consumed across AI concierge interactions.', max_digits=12, verbose_name='Cumulative AI Spend (USD)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(help_text='Host tenant firm/organization that owns this client account.', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='tenants.organization', verbose_name='Organization / Tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
