# Generated by Django 5.1.15 on 2026-09-09 17:37

import apps.media.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('file', models.FileField(help_text='Binary file uploaded to media storage.', max_length=512, upload_to=apps.media.models.document_upload_to_path, verbose_name='File')),
                ('filename', models.CharField(db_index=True, help_text='Original display filename of the document.', max_length=255, verbose_name='Filename')),
                ('file_size', models.BigIntegerField(default=0, help_text='Exact size of the binary file in bytes.', verbose_name='File Size (Bytes)')),
                ('mime_type', models.CharField(db_index=True, default='application/octet-stream', help_text='Detected Content-Type / MIME string.', max_length=128, verbose_name='MIME Type')),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, default='', help_text='64-character hexadecimal SHA-256 digest for deduplication and integrity.', max_length=64, verbose_name='SHA-256 Checksum')),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Indicates if document can be accessed publicly without token authentication.', verbose_name='Is Public')),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='Primary key of attached target entity.', max_length=255, null=True, verbose_name='Object ID')),
                ('extra_metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value metadata (e.g. dimensions, page count, tags).', verbose_name='Extra Metadata')),
                ('content_type', models.ForeignKey(blank=True, help_text='Model type of attached target entity.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization / workspace owning this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User or bot service account that uploaded this document.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'checksum_sha256'], name='media_docum_organiz_a27908_idx'), models.Index(fields=['content_type', 'object_id'], name='media_docum_content_67cc57_idx'), models.Index(fields=['organization', 'uploaded_by', '-created_at'], name='media_docum_organiz_7e9e66_idx')],
            },
        ),
    ]
