# Generated by Django 5.1.15 on 2026-09-11 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0001_initial'),
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Associated client entity if this document belongs to a specific client.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client', '-created_at'], name='media_docum_client__015b2f_idx'),
        ),
    ]
