# Generated by Django 5.1.15 on 2026-09-09 16:05

import apps.tenants.models
import django.db.models.deletion
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('name', models.CharField(help_text='Display name of the organization or workspace.', max_length=255, verbose_name='Organization Name')),
                ('slug', models.SlugField(help_text="Unique URL-friendly workspace identifier (e.g. 'acme-corp').", max_length=100, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if this organization is active and operational.', verbose_name='Is Active')),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], db_index=True, default='free', help_text='Service tier determining feature limits and entitlements.', max_length=32, verbose_name='Subscription Tier')),
                ('max_users', models.PositiveIntegerField(default=10, help_text='Maximum number of seats permitted for this organization.', verbose_name='Maximum Users')),
                ('domain', models.CharField(blank=True, help_text='Optional custom domain or email domain mapped to this tenant.', max_length=255, null=True, unique=True, verbose_name='Custom / Email Domain')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary workspace configuration and tenant preferences.', verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Email address of the invitee.', max_length=254, verbose_name='Invited Email')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer'), ('guest', 'Guest')], default='member', help_text='Role granted to the user upon accepting the invitation.', max_length=32, verbose_name='Role')),
                ('token', models.CharField(db_index=True, default=secrets.token_urlsafe, max_length=64, unique=True, verbose_name='Invitation Token')),
                ('expires_at', models.DateTimeField(default=apps.tenants.models.default_invitation_expiry, verbose_name='Expires At')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=32, verbose_name='Status')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_org_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Invitation',
                'verbose_name_plural': 'Organization Invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique universal identifier for this record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer'), ('guest', 'Guest')], db_index=True, default='member', help_text='Role determining workspace permissions.', max_length=32, verbose_name='Membership Role')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this user membership is active.', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(help_text='The organization workspace.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(help_text='The member user.', on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='unique_org_user_membership')],
            },
        ),
    ]
