# Generated by Django 5.1.15 on 2026-09-09 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('name', models.CharField(db_index=True, help_text='Human-readable name of the report template.', max_length=255, verbose_name='Template Name')),
                ('slug', models.SlugField(help_text='Unique identifier slug used for API and automation execution.', max_length=255, unique=True, verbose_name='Template Slug')),
                ('description', models.TextField(blank=True, default='', help_text='Detailed documentation on report contents and usage.', verbose_name='Description')),
                ('target_model', models.CharField(db_index=True, help_text="Model identifier e.g. 'auth.User', 'integration.AgentTask', 'crm.lead'.", max_length=255, verbose_name='Target Model')),
                ('page_format', models.CharField(choices=[('A4', 'A4 Standard (210 x 297 mm)'), ('Letter', 'US Letter (8.5 x 11 in)'), ('Legal', 'US Legal (8.5 x 14 in)'), ('thermal_80mm', 'Thermal Receipt (80mm Roll)')], default='A4', help_text='Paper size specification.', max_length=32, verbose_name='Page Format')),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', help_text='Page layout orientation (Portrait or Landscape).', max_length=16, verbose_name='Orientation')),
                ('layout_schema', models.JSONField(blank=True, default=dict, help_text='JSON visual coordinate tree for visual drag-and-drop report builders.', verbose_name='Layout Schema')),
                ('compiled_html', models.TextField(blank=True, default='', help_text='Jinja2 / Django HTML template markup with variable placeholders.', verbose_name='HTML Template')),
                ('css_styles', models.TextField(blank=True, default='', help_text='Custom CSS rules applied during PDF generation (including @page media rules).', verbose_name='CSS Stylesheet')),
                ('header_html', models.TextField(blank=True, default='', help_text='Running page header HTML content.', verbose_name='Header HTML')),
                ('footer_html', models.TextField(blank=True, default='', help_text='Running page footer HTML content with page counters.', verbose_name='Footer HTML')),
                ('is_default', models.BooleanField(default=False, help_text='Default report template for the specified target model.', verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for rendering.', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization / workspace owning this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('format', models.CharField(choices=[('html', 'HTML Preview'), ('pdf', 'Vector PDF Document')], default='pdf', max_length=16, verbose_name='Output Format')),
                ('record_id', models.CharField(blank=True, db_index=True, default='', help_text='Primary key of target model record evaluated in this report run.', max_length=255, verbose_name='Record ID')),
                ('duration_ms', models.IntegerField(default=0, help_text='Execution time in milliseconds.', verbose_name='Duration (ms)')),
                ('file_size_bytes', models.IntegerField(default=0, verbose_name='File Size (Bytes)')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=16, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requesting Actor')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_execution_logs', to='media.document', verbose_name='Generated Document')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization / workspace owning this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='reports.reporttemplate', verbose_name='Report Template')),
            ],
            options={
                'verbose_name': 'Report Execution Log',
                'verbose_name_plural': 'Report Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'target_model', 'is_active'], name='reports_rep_organiz_6de2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['slug'], name='reports_rep_slug_b711d0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecutionlog',
            index=models.Index(fields=['organization', '-created_at'], name='reports_rep_organiz_419139_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecutionlog',
            index=models.Index(fields=['template', 'status'], name='reports_rep_templat_4841af_idx'),
        ),
    ]
