# Generated by Django 5.1.15 on 2026-09-09 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_create_default_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('name', models.CharField(help_text="Display label (e.g. 'GitHub Repository Push Webhook').", max_length=100, verbose_name='Webhook Name')),
                ('endpoint_slug', models.SlugField(help_text="Unique URL path parameter (e.g. '/api/v1/gateway/webhooks/github-push/ingest/').", max_length=100, unique=True, verbose_name='Endpoint Slug')),
                ('secret_token', models.CharField(help_text='Shared secret used to compute and verify incoming HMAC signatures.', max_length=255, verbose_name='Secret Token / HMAC Key')),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('stripe', 'Stripe'), ('slack', 'Slack'), ('custom', 'Custom HMAC')], default='custom', help_text='Provider signature format for HMAC verification.', max_length=64, verbose_name='Provider')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enables or disables inbound event ingestion.', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization / workspace owning this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Inbound Webhook Endpoint',
                'verbose_name_plural': 'Inbound Webhook Endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('name', models.CharField(help_text="Human-readable label identifying this API key (e.g. 'Stripe Integration Key').", max_length=100, verbose_name='Key Name')),
                ('prefix', models.CharField(db_index=True, help_text="Public key prefix for fast database lookup (e.g. 'agy_live_a1b2').", max_length=16, verbose_name='Key Prefix')),
                ('hashed_key', models.CharField(help_text='SHA-256 hash digest of the full secret key.', max_length=128, verbose_name='Hashed Secret Key')),
                ('scopes', models.JSONField(blank=True, default=list, help_text="List of allowed action scopes (e.g. ['read', 'write', 'tasks:create']).", verbose_name='Permission Scopes')),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Optional list of allowed client IP addresses/CIDR blocks.', verbose_name='Allowed IP Addresses')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration timestamp. Null indicates an unexpiring key.', null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Indicates if key is operational and authorized.', verbose_name='Is Active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp of most recent successful authentication.', null=True, verbose_name='Last Used At')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization / workspace owning this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('user', models.ForeignKey(help_text='User or bot account bound to this API key.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Developer API Key',
                'verbose_name_plural': 'Developer API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['prefix', 'is_active'], name='api_gateway_prefix_80368e_idx'), models.Index(fields=['organization', 'user', 'is_active'], name='api_gateway_organiz_c659cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was originally created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted.', verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted.', null=True, verbose_name='Deleted At')),
                ('event_type', models.CharField(db_index=True, help_text="Detected provider event name (e.g. 'push', 'payment_intent.succeeded').", max_length=128, verbose_name='Event Type')),
                ('payload', models.JSONField(default=dict, help_text='Raw JSON payload received from sender.', verbose_name='Payload Body')),
                ('headers', models.JSONField(default=dict, help_text='Received HTTP headers dictionary.', verbose_name='HTTP Headers')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32, verbose_name='Execution Status')),
                ('error_message', models.TextField(blank=True, default='', help_text='Details if processing or signature validation failed.', verbose_name='Error Message')),
                ('created_by', models.ForeignKey(blank=True, help_text='User or service account who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization / workspace owning this record.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.organization', verbose_name='Organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User or service account who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api_gateway.inboundwebhook', verbose_name='Inbound Webhook')),
            ],
            options={
                'verbose_name': 'Webhook Event Log',
                'verbose_name_plural': 'Webhook Event Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['webhook', 'status', '-created_at'], name='api_gateway_webhook_a9056a_idx'), models.Index(fields=['organization', 'event_type'], name='api_gateway_organiz_8f9ea5_idx')],
            },
        ),
    ]
